### ISSUE TITLE
Security issue: log_for_artena logs to webroot

### ISSUE THREAD

**Issue by danmarsden** [smss-dev/moodle-artena-interface#3]
quick fix would be to change log_for_artena to store the logs within $CFG->dataroot but it looks like logs are always "on" - is that correct?

**Comment by smss-dev** [comment]
Will have to go for the quick fix in the short term.  Will be adding better reporting to the requesting client in the next release cycle of our product.

**Comment by danmarsden** [comment]
cool - as long as it's not storing logs within the publicly accessible webroot which we don't typically allow write access to anyway. Thanks!

**Comment by danmarsden** [comment]
good to see the main security issue fixed here - Thanks. it would still be nice for there to be a way to turn the logging off or to see some more obvious log file rotation happening. Also - the parameter "method" should probably be verified/cleaned to make sure it only contains alphanumeric and not "../../" style strings. but as this is only called by your code and the strings all look fine this is probably ok.
